// Build the photo archive wall from hand-picked crops of the Petoskey 80s/90s source folder.
//   node tools/archive.mjs
// Reads every $ARCHIVE_CROPS/crops-*.jsonl (one crop per line:
//   {"src","id","x","y","w","h","alt","era","treatment":"xerox|color","weight"}, x/y/w/h = fractions of the source, top-left origin),
// cuts each crop out of $ARCHIVE_SRC/<src>, treats it like tools/own.mjs, and writes $ARCHIVE_OUT/<id>.jpg
// (max 800px, stripped) plus $ARCHIVE_OUT/manifest.json and $ARCHIVE_OUT/ATTRIBUTION.md.
// Credits come from $ARCHIVE_ATTRIBUTION (the source folder's ATTRIBUTION.md table). Reruns overwrite.
// Env: ARCHIVE_SRC (/Users/pc/Desktop/petoskey-80s-90s), ARCHIVE_CROPS (archive), ARCHIVE_OUT (photos/archive),
//      ARCHIVE_ATTRIBUTION ($ARCHIVE_SRC/ATTRIBUTION.md), ARCHIVE_QUALITY (78).
import { readFileSync, writeFileSync, readdirSync, existsSync, mkdirSync } from 'node:fs';
import { join } from 'node:path';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

export const TREATMENTS = {
  xerox: ['-colorspace', 'Gray', '-brightness-contrast', '5x25', '-attenuate', '0.35', '+noise', 'Gaussian'],
  color: ['-colorspace', 'sRGB'],
};

export function parseCrops(dir) {
  const files = readdirSync(dir).filter((f) => /^crops-.*\.jsonl$/.test(f)).sort();
  const crops = [];
  for (const file of files) {
    readFileSync(join(dir, file), 'utf8').split('\n').forEach((line, i) => {
      if (!line.trim()) return;
      try { crops.push(JSON.parse(line)); }
      catch (e) { throw new Error(`${file} line ${i + 1}: ${e.message}`); }
    });
  }
  return crops;
}

// Desktop ATTRIBUTION.md: | Filename | Year/era | Description | Source + URL | Credit/rights |
// Source cell is "<name> <url>" (or a markdown link [name](url)).
export function parseAttribution(text) {
  const map = new Map();
  for (const line of text.split('\n')) {
    if (!line.startsWith('| ')) continue;
    const cells = line.slice(1, line.endsWith('|') ? -1 : undefined).split('|').map((c) => c.trim());
    if (cells.length < 5 || !/\.\w+$/.test(cells[0]) || cells[0] === 'Filename') continue;
    const [file, , title, source, license] = cells;
    const link = source.match(/\[([^\]]*)\]\((https?:\/\/[^)\s]+)\)/);
    const url = link ? link[2] : (source.match(/https?:\/\/\S+/) || [''])[0];
    const author = (link ? source.replace(link[0], link[1]) : source.replace(url, '')).replace(/\s+/g, ' ').trim().replace(/[,;:\-–]+$/, '').trim();
    map.set(file, { title, source_url: url, author, license });
  }
  return map;
}

const esc = (s) => String(s ?? '').replace(/\|/g, '\\|').replace(/\n/g, ' ');

export function buildArchive({ src, crops, out, attribution, quality = 78, log = console.error }) {
  const list = parseCrops(crops);
  let credits = new Map();
  if (existsSync(attribution)) credits = parseAttribution(readFileSync(attribution, 'utf8'));
  else log(`warn: no attribution file at ${attribution}`);
  mkdirSync(out, { recursive: true });
  const manifest = [];
  let skipped = 0;
  for (const c of list) {
    const from = join(src, c.src);
    if (!existsSync(from)) { log(`warn: skip ${c.id}: source missing ${c.src}`); skipped++; continue; }
    const ops = TREATMENTS[c.treatment];
    if (!ops) throw new Error(`crop ${c.id}: unknown treatment ${c.treatment}`);
    const [sw, sh] = execFileSync('magick', ['identify', '-format', '%w %h', `${from}[0]`]).toString().trim().split(' ').map(Number);
    const geom = `${Math.round(c.w * sw)}x${Math.round(c.h * sh)}+${Math.round(c.x * sw)}+${Math.round(c.y * sh)}`;
    const file = `${c.id}.jpg`;
    const dest = join(out, file);
    execFileSync('magick', [`${from}[0]`, '-gravity', 'NorthWest', '-crop', geom, '+repage', ...ops,
      '-resize', '800x800>', '-strip', '-quality', String(quality), dest]);
    const [w, h] = execFileSync('magick', ['identify', '-format', '%w %h', dest]).toString().trim().split(' ').map(Number);
    const credit = credits.get(c.src);
    if (!credit) log(`warn: no attribution row for ${c.src} (crop ${c.id})`);
    const { source_url = '', title = '', author = '', license = '' } = credit || {};
    manifest.push({ file, alt: c.alt ?? '', era: c.era ?? '', treatment: c.treatment, weight: c.weight, w, h, source_url, title, author, license });
  }
  writeFileSync(join(out, 'manifest.json'), JSON.stringify(manifest, null, 1) + '\n');
  const rows = manifest.map((m) => {
    const text = esc(m.title || m.author || m.source_url);
    const source = m.source_url ? `[${text}](${m.source_url})` : text;
    return `| ${m.file} | ${esc(m.era)} | ${esc(m.alt)} | ${source} | ${esc(m.license)} |`;
  });
  writeFileSync(join(out, 'ATTRIBUTION.md'), [
    '# Archive photo credits', '', 'Generated by `node tools/archive.mjs` from `archive/crops-*.jsonl`. Do not edit by hand.', '',
    '| file | era | alt | source | credit |', '|---|---|---|---|---|', ...rows, '',
  ].join('\n'));
  return { written: manifest.length, skipped, manifest };
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const src = process.env.ARCHIVE_SRC || '/Users/pc/Desktop/petoskey-80s-90s';
  const out = process.env.ARCHIVE_OUT || 'photos/archive';
  const res = buildArchive({
    src, out,
    crops: process.env.ARCHIVE_CROPS || 'archive',
    attribution: process.env.ARCHIVE_ATTRIBUTION || join(src, 'ATTRIBUTION.md'),
    quality: +(process.env.ARCHIVE_QUALITY || 78),
  });
  console.log(`archive: wrote ${res.written} to ${out}, skipped ${res.skipped}`);
}
