// Cut the hand-picked crops of the Petoskey 80s/90s source folder; the picks join the wall as ordinary photos.
//   node tools/archive.mjs && node build.mjs
// Reads every $ARCHIVE_CROPS/crops-*.jsonl (one crop per line:
//   {"src","id","x","y","w","h","alt","era","treatment":"xerox|color","weight"}, x/y/w/h = fractions of the source, top-left origin)
// and cuts each crop out of $ARCHIVE_SRC/<src>, treated like tools/own.mjs (max 800px, stripped).
// The knob is $ARCHIVE_CROPS/pick.json: a JSON array of crop ids or {"id","weight"}. The picks are written to
// $ARCHIVE_OUT/<id>.jpg and appended, in pick order, to $ARCHIVE_OUT/manifest.json and ATTRIBUTION.md as ordinary
// wall photos (license "Archive scan: <original credit>", weight from pick.json or the crop's clamped to 5-7).
// Reruns replace only the tool's own entries (files named after a crop id); unpicked crops' jpgs, entries and rows
// are removed, nothing else is touched. Every crop, picked or not, is also cut into $ARCHIVE_HELD with its own
// manifest.json + ATTRIBUTION.md, so the rest are kept for later. No pick.json: every crop joins the wall.
// Credits come from $ARCHIVE_ATTRIBUTION (the source folder's ATTRIBUTION.md table).
// Env: ARCHIVE_SRC (/Users/pc/Desktop/petoskey-80s-90s), ARCHIVE_CROPS (archive), ARCHIVE_OUT (photos),
//      ARCHIVE_HELD ($ARCHIVE_SRC/crops), ARCHIVE_ATTRIBUTION ($ARCHIVE_SRC/ATTRIBUTION.md), ARCHIVE_QUALITY (78).
import { readFileSync, writeFileSync, readdirSync, existsSync, mkdirSync, copyFileSync, unlinkSync } from 'node:fs';
import { join } from 'node:path';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

export const TREATMENTS = {
  xerox: ['-colorspace', 'Gray', '-brightness-contrast', '5x25', '-attenuate', '0.35', '+noise', 'Gaussian'],
  color: ['-colorspace', 'sRGB'],
};

export function parseCrops(dir) {
  const files = readdirSync(dir).filter((f) => /^crops-.*\.jsonl$/.test(f)).sort();
  const crops = [];
  for (const file of files) {
    readFileSync(join(dir, file), 'utf8').split('\n').forEach((line, i) => {
      if (!line.trim()) return;
      try { crops.push(JSON.parse(line)); }
      catch (e) { throw new Error(`${file} line ${i + 1}: ${e.message}`); }
    });
  }
  return crops;
}

// Desktop ATTRIBUTION.md: | Filename | Year/era | Description | Source + URL | Credit/rights |
// Source cell is "<name> <url>" (or a markdown link [name](url)).
export function parseAttribution(text) {
  const map = new Map();
  for (const line of text.split('\n')) {
    if (!line.startsWith('| ')) continue;
    const cells = line.slice(1, line.endsWith('|') ? -1 : undefined).split('|').map((c) => c.trim());
    if (cells.length < 5 || !/\.\w+$/.test(cells[0]) || cells[0] === 'Filename') continue;
    const [file, , title, source, license] = cells;
    const link = source.match(/\[([^\]]*)\]\((https?:\/\/[^)\s]+)\)/);
    const url = link ? link[2] : (source.match(/https?:\/\/\S+/) || [''])[0];
    const author = (link ? source.replace(link[0], link[1]) : source.replace(url, '')).replace(/\s+/g, ' ').trim().replace(/[,;:\-–]+$/, '').trim();
    map.set(file, { title, source_url: url, author, license });
  }
  return map;
}

const esc = (s) => String(s ?? '').replace(/\|/g, '\\|').replace(/\n/g, ' ');

// the held pile: every crop with its era and original weight, credits in their own table
function writeHeld(dir, manifest) {
  writeFileSync(join(dir, 'manifest.json'), JSON.stringify(manifest, null, 1) + '\n');
  const rows = manifest.map((m) => {
    const text = esc(m.title || m.author || m.source_url);
    const source = m.source_url ? `[${text}](${m.source_url})` : text;
    return `| ${m.file} | ${esc(m.era)} | ${esc(m.alt)} | ${source} | ${esc(m.license)} |`;
  });
  writeFileSync(join(dir, 'ATTRIBUTION.md'), [
    '# Archive photo credits', '', 'Generated by `node tools/archive.mjs` from `archive/crops-*.jsonl`. Do not edit by hand.', '',
    '| file | era | alt | source | credit |', '|---|---|---|---|---|', ...rows, '',
  ].join('\n'));
}

// the knob: archive/pick.json, crop ids (or {id, weight, caption?, alt?}) to put on the wall; null when there is none
export function readPick(crops, list) {
  const file = join(crops, 'pick.json');
  if (!existsSync(file)) return null;
  const raw = JSON.parse(readFileSync(file, 'utf8'));
  if (!Array.isArray(raw)) throw new Error(`${file}: expected a JSON array of crop ids`);
  const pick = raw.map((p) => (typeof p === 'string' ? { id: p } : p));
  const ids = new Set(list.map((c) => c.id));
  const unknown = pick.filter((p) => !ids.has(p.id)).map((p) => p.id);
  if (unknown.length) throw new Error(`pick.json: no crop with id ${unknown.join(', ')}`);
  return pick;
}

const clamp = (n) => Math.min(7, Math.max(5, Math.round(n ?? 6)));

export function buildArchive({ src, crops, out, held, attribution, quality = 78, log = console.error }) {
  const list = parseCrops(crops);
  const pick = readPick(crops, list) || list.map((c) => ({ id: c.id }));
  const picked = new Set(pick.map((p) => p.id));
  let credits = new Map();
  if (existsSync(attribution)) credits = parseAttribution(readFileSync(attribution, 'utf8'));
  else log(`warn: no attribution file at ${attribution}`);
  // with a pick.json, every crop is cut into the held dir and the picks are copied onto the wall from there
  const keepAll = existsSync(join(crops, 'pick.json')) && held;
  const cutTo = keepAll ? held : out;
  mkdirSync(out, { recursive: true });
  if (keepAll) mkdirSync(held, { recursive: true });
  const cut = new Map();
  let skipped = 0;
  for (const c of keepAll ? list : list.filter((c) => picked.has(c.id))) {
    const from = join(src, c.src);
    if (!existsSync(from)) { log(`warn: skip ${c.id}: source missing ${c.src}`); skipped++; continue; }
    const ops = TREATMENTS[c.treatment];
    if (!ops) throw new Error(`crop ${c.id}: unknown treatment ${c.treatment}`);
    const [sw, sh] = execFileSync('magick', ['identify', '-format', '%w %h', `${from}[0]`]).toString().trim().split(' ').map(Number);
    const geom = `${Math.round(c.w * sw)}x${Math.round(c.h * sh)}+${Math.round(c.x * sw)}+${Math.round(c.y * sh)}`;
    const file = `${c.id}.jpg`;
    const dest = join(cutTo, file);
    execFileSync('magick', [`${from}[0]`, '-gravity', 'NorthWest', '-crop', geom, '+repage', ...ops,
      '-resize', '800x800>', '-strip', '-quality', String(quality), dest]);
    const [w, h] = execFileSync('magick', ['identify', '-format', '%w %h', dest]).toString().trim().split(' ').map(Number);
    const credit = credits.get(c.src);
    if (!credit) log(`warn: no attribution row for ${c.src} (crop ${c.id})`);
    const { source_url = '', title = '', author = '', license = '' } = credit || {};
    cut.set(c.id, { file, alt: c.alt ?? '', era: c.era ?? '', treatment: c.treatment, weight: c.weight, w, h, source_url, title, author, license });
  }
  if (keepAll) writeHeld(held, [...cut.values()]);

  // the wall: drop every entry, row and jpg this tool owns (named after a crop id), then add the picks back
  const own = new Set(list.map((c) => `${c.id}.jpg`));
  const entries = pick.filter((p) => cut.has(p.id)).map((p) => {
    const m = cut.get(p.id);
    if (keepAll) copyFileSync(join(held, m.file), join(out, m.file));
    return { file: m.file, alt: p.alt ?? m.alt, source_url: m.source_url, title: m.title, author: m.author,
      license: m.license ? `Archive scan: ${m.license}` : 'Archive scan', license_url: '', treatment: m.treatment,
      weight: p.weight ?? clamp(m.weight), w: m.w, h: m.h, caption: p.caption ?? '' };
  });
  const mfile = join(out, 'manifest.json');
  const manifest = (existsSync(mfile) ? JSON.parse(readFileSync(mfile, 'utf8')) : []).filter((m) => !own.has(m.file)).concat(entries);
  // ASCII-only, non-ASCII \u-escaped, the way the committed photos/manifest.json is written
  const ascii = (v) => JSON.stringify(v, null, 1).replace(/[\u0080-\uffff]/g, (c) => '\\u' + c.charCodeAt(0).toString(16).padStart(4, '0'));
  writeFileSync(mfile, ascii(manifest) + '\n');
  const afile = join(out, 'ATTRIBUTION.md');
  const lines = (existsSync(afile) ? readFileSync(afile, 'utf8') : '# Photo credits\n\n| File | Original | Author | License | Treatment |\n|---|---|---|---|---|\n')
    .split('\n').filter((l) => !(l.startsWith('| ') && own.has(l.slice(2, l.indexOf(' |', 2)))));
  let last = lines.length - 1;
  while (last >= 0 && !lines[last].startsWith('|')) last--;
  lines.splice(last + 1, 0, ...entries.map((e) => {
    const text = esc(e.title || e.author || e.source_url);
    return `| ${e.file} | ${e.source_url ? `[${text}](${e.source_url})` : text} | ${esc(e.author)} | ${esc(e.license)} | ${e.treatment} |`;
  }));
  writeFileSync(afile, lines.join('\n'));
  const ship = new Set(entries.map((e) => e.file));
  for (const f of readdirSync(out)) if (own.has(f) && !ship.has(f)) unlinkSync(join(out, f));
  return { written: entries.length, held: keepAll ? cut.size : 0, skipped, manifest: entries };
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const src = process.env.ARCHIVE_SRC || '/Users/pc/Desktop/petoskey-80s-90s';
  const out = process.env.ARCHIVE_OUT || 'photos';
  const held = process.env.ARCHIVE_HELD || join(src, 'crops');
  const res = buildArchive({
    src, out, held,
    crops: process.env.ARCHIVE_CROPS || 'archive',
    attribution: process.env.ARCHIVE_ATTRIBUTION || join(src, 'ATTRIBUTION.md'),
    quality: +(process.env.ARCHIVE_QUALITY || 78),
  });
  console.log(`archive: wrote ${res.written} to ${out}${res.held ? `, held ${res.held} in ${held}` : ''}, skipped ${res.skipped}`);
}
